/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/drops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home list */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            server_time?: string;
                            drops?: components["schemas"]["DropSummary"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drops/{drop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiers, phase, counts, config_hash, drand_round, server_time */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DropDetail"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mock platform; username to identity JWT with risk facts */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drops/{drop_id}/pow-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Challenge bound to the caller's identity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PowChallenge"];
                    };
                };
                401: components["responses"]["Error"];
                /** @description window_closed */
                403: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drops/{drop_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create entry, return signed receipt */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EntryRequest"];
                };
            };
            responses: {
                /** @description Identical retry; same receipt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntryResponse"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntryResponse"];
                    };
                };
                /** @description turnstile_failed | unknown_tier | quantity_exceeds_max */
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                /** @description window_closed */
                403: components["responses"]["Error"];
                /** @description entry_exists_different_terms */
                409: components["responses"]["Error"];
                /** @description invalid_request (e.g. wrong number of nonces) */
                422: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drops/{drop_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Canonical snapshot bytes and the timestamp proof
         * @description Body is the stored canonical blob, byte for byte (newline-delimited JSON).
         *     Headers carry the evidence:
         *       X-Fairdrop-Snapshot-Sha256: hex
         *       X-Fairdrop-Exclusions-Sha256: hex
         *       X-Fairdrop-Sealed-At: ISO time
         *       X-Fairdrop-Timestamped-At: ISO time (absent until stamped)
         *       X-Fairdrop-Timestamp-Proof: base64 of the timestamp_proof JSON (absent until stamped)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-ndjson": string;
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drops/{drop_id}/exclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Excluded entry_ids with the rule that fired (stored blob, byte for byte) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-ndjson": string;
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public key for receipt signatures */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Keys"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drops/{drop_id}/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caller's entry, status, rank, offer */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drops/{drop_id}/draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** drand evidence, ranked entry_ids, initial allocation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Draw"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{offer_id}/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock the offer and open the payment window */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    offer_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        order_id: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            offer_id?: string;
                            order_id?: string;
                            status?: components["schemas"]["OfferStatus"];
                            /** Format: date-time */
                            pay_deadline?: string;
                        };
                    };
                };
                /** @description offer_not_yours */
                403: components["responses"]["Error"];
                /** @description offer_expired | already_redeemed_other_order | not_offered | seats_not_selected */
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{offer_id}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Razorpay order for the caller's pending offer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    offer_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Checkout"];
                    };
                };
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
                /** @description not_payment_pending */
                409: components["responses"]["Error"];
                /** @description payment_unavailable */
                503: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{offer_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit mock result or verified Razorpay payment identifiers */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    offer_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MockPayment"] | components["schemas"]["RazorpayPayment"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "confirmed" | "payment_failed";
                        };
                    };
                };
                /** @description payment_window_closed (refund: true) | not_payment_pending | payment_unavailable */
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{offer_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release an offer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    offer_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drops/{drop_id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seat map after the draw. Green = absent, amber = locked, red = booked. Owners are never shown. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SeatMap"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{offer_id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's seat choice and their rank-ordered seat window */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    offer_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OfferSeats"];
                    };
                };
                /** @description offer_not_yours */
                403: components["responses"]["Error"];
            };
        };
        /**
         * Replace the caller's seat choice (0..quantity seats), atomically, during their wave window
         * @description Newly chosen seats are locked for this offer; dropped seats are released. If any newly
         *     chosen seat is already locked or booked, nothing changes: 409 seat_taken with `seats`.
         *     Seats freeze when the offer is redeemed; paying books them, failing or expiring releases them.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    offer_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        seats: number[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OfferSeats"];
                    };
                };
                /** @description too_many_seats | invalid_seat */
                400: components["responses"]["Error"];
                /** @description offer_not_yours */
                403: components["responses"]["Error"];
                /** @description seat_taken (seats) | seat_window_not_open (opens_at) | not_offered | offer_expired | seat_selection_disabled */
                409: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drops/{drop_id}/invariants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** held against capacity, duplicate counters */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invariants"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create drop, compute drand_round and config_hash */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDropRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DropDetail"];
                    };
                };
                401: components["responses"]["Error"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drops/{drop_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open now (demo) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drops/{drop_id}/seal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seal now (demo). Idempotent; resumes an interrupted seal or retries the timestamp. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drops/{drop_id}/draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draw once round R is available */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drops/{drop_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** entry_id, identity_id, quantity, status, for harness scoring */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drop_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wipe and reseed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default true */
                        seed_demo_drop?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Phase: "scheduled" | "open" | "sealed" | "drawn" | "settled";
        /** @enum {string} */
        OfferStatus: "offered" | "payment_pending" | "confirmed" | "expired" | "declined" | "payment_failed";
        /** @enum {string} */
        EntryStatus: "registered" | "excluded" | "waitlisted" | "offered" | "payment_pending" | "confirmed" | "expired" | "declined" | "payment_failed" | "not_selected";
        /** @enum {string} */
        ErrorCode: "window_closed" | "entry_exists_different_terms" | "unknown_tier" | "quantity_exceeds_max" | "turnstile_failed" | "offer_expired" | "offer_not_yours" | "already_redeemed_other_order" | "not_offered" | "payment_window_closed" | "not_payment_pending" | "payment_unavailable" | "seat_taken" | "seat_window_not_open" | "seats_not_selected" | "too_many_seats" | "invalid_seat" | "seat_selection_disabled";
        /** @enum {string} */
        TransportError: "unauthorized" | "invalid_request" | "not_found" | "rate_limited" | "conflict";
        Error: {
            /** @description ErrorCode or TransportError */
            error: string;
            message?: string;
            /** @description Only on payment_window_closed */
            refund?: boolean;
        };
        SybilRule: {
            id: string;
            /** @enum {string} */
            kind: "max_per_device" | "max_per_payment" | "min_account_age_s";
            /** @description max_per_* rules */
            limit?: number;
            /** @description min_account_age_s, seconds */
            value?: number;
        };
        Tier: {
            tier_id: string;
            name: string;
            price_paise: number;
            capacity: number;
        };
        DropSummary: {
            /** Format: uuid */
            drop_id: string;
            name: string;
            venue: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            opens_at: string;
            /** Format: date-time */
            closes_at: string;
            phase: components["schemas"]["Phase"];
            /** @enum {string} */
            allocation_mode: "lottery_wil" | "fcfs";
        };
        DropDetail: components["schemas"]["DropSummary"] & {
            tiers: components["schemas"]["Tier"][];
            pow_required?: boolean;
            turnstile_required?: boolean;
            pow_bits?: number;
            pow_k?: number;
            pow_memory_kib?: number;
            max_quantity?: number;
            offer_ttl_s?: number;
            pay_deadline_s?: number;
            max_promotion_rounds?: number;
            /** @description winners choose exact seats after the draw */
            seat_selection?: boolean;
            /** @description offers per tier per seat-choice wave, in rank order */
            seat_wave_size?: number;
            /** @description seconds between seat-choice waves */
            seat_wave_s?: number;
            sybil_rules?: components["schemas"]["SybilRule"][];
            config_hash: string;
            drand_chain: string;
            drand_round: number;
            /** Format: date-time */
            drand_round_due_at: string;
            /** Format: date-time */
            server_time: string;
            counts: {
                entries?: number;
                /** @description null until sealed */
                eligible?: number | null;
                /** @description null until sealed */
                excluded?: number | null;
            };
            /** @description null until the snapshot exists */
            snapshot?: {
                canonical_hash?: string;
                exclusions_hash?: string;
                /** Format: date-time */
                sealed_at?: string;
                /** Format: date-time */
                timestamped_at?: string | null;
            } | null;
        };
        CreateDropRequest: {
            /**
             * Format: uuid
             * @description optional; generated if absent
             */
            drop_id?: string;
            name: string;
            venue: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            opens_at: string;
            /** Format: date-time */
            closes_at: string;
            /** @enum {string} */
            allocation_mode: "lottery_wil" | "fcfs";
            pow_required: boolean;
            turnstile_required: boolean;
            pow_bits: number;
            /** @default 16 */
            pow_k: number;
            /** @default 2048 */
            pow_memory_kib: number;
            /** @default 4 */
            max_quantity: number;
            /** @default 600 */
            offer_ttl_s: number;
            /** @default 300 */
            pay_deadline_s: number;
            /** @default 6 */
            max_promotion_rounds: number;
            /** @default false */
            seat_selection: boolean;
            /** @default 25 */
            seat_wave_size: number;
            /** @default 30 */
            seat_wave_s: number;
            sybil_rules?: components["schemas"]["SybilRule"][];
            tiers: components["schemas"]["Tier"][];
        };
        LoginRequest: {
            username: string;
            device_hash?: string;
            payment_fingerprint?: string;
            account_age_days?: number;
        };
        LoginResponse: {
            token: string;
            identity_id: string;
            /** Format: date-time */
            expires_at: string;
        };
        PowChallenge: {
            challenge: string;
            /** Format: date-time */
            issued_at: string;
            bits: number;
            k: number;
            memory_kib: number;
        };
        EntryRequest: {
            tier_id: string;
            quantity: number;
            turnstile_token?: string;
            pow?: {
                /** Format: date-time */
                issued_at: string;
                nonces: number[];
            };
        };
        Receipt: {
            /** Format: uuid */
            drop_id: string;
            entry_id: string;
            tier_id: string;
            quantity: number;
            config_hash: string;
            /** @description microsecond precision, ends in Z */
            accepted_at: string;
        };
        EntryResponse: {
            entry_id: string;
            receipt: components["schemas"]["Receipt"];
            /** @description base64 Ed25519 over canonical receipt bytes */
            receipt_sig: string;
        };
        Keys: {
            receipt: {
                /** @constant */
                alg?: "Ed25519";
                /** @description base64 raw 32-byte key */
                public_key?: string;
                kid?: string;
            };
        };
        Me: {
            phase: components["schemas"]["Phase"];
            /** Format: date-time */
            server_time: string;
            entry: {
                entry_id?: string;
                tier_id?: string;
                quantity?: number;
                status?: components["schemas"]["EntryStatus"];
                rank?: number | null;
                waitlist_position?: number | null;
                exclusion_reason?: string | null;
            } | null;
            offer: {
                /** Format: uuid */
                offer_id?: string;
                tier_id?: string;
                quantity?: number;
                amount_paise?: number;
                round?: number;
                status?: components["schemas"]["OfferStatus"];
                /** Format: date-time */
                expires_at?: string;
                /** Format: date-time */
                pay_deadline?: string | null;
            } | null;
        };
        Draw: {
            /** Format: uuid */
            drop_id: string;
            round: number;
            signature: string;
            randomness: string;
            relays: string[];
            /** Format: date-time */
            drawn_at: string;
            ranked_entry_ids: string[];
            allocation: {
                entry_id: string;
                tier_id: string;
                quantity: number;
                round: number;
                /** Format: uuid */
                offer_id: string;
            }[];
        };
        SeatMap: {
            /** Format: uuid */
            drop_id: string;
            seat_selection: boolean;
            /** Format: date-time */
            server_time: string;
            tiers: {
                tier_id: string;
                capacity: number;
                /** @description amber: held by an offer choosing or paying */
                locked: number[];
                /** @description red: paid */
                booked: number[];
            }[];
        };
        OfferSeats: {
            /** Format: uuid */
            offer_id: string;
            /** Format: uuid */
            drop_id?: string;
            tier_id: string;
            quantity: number;
            round?: number;
            status: components["schemas"]["OfferStatus"];
            seat_selection: boolean;
            /** @description this offer's seats, 0-based row-major indexes */
            seats: number[];
            /** Format: date-time */
            window_opens_at: string;
            /** Format: date-time */
            window_closes_at: string;
            window_open: boolean;
            /** Format: date-time */
            server_time?: string;
        };
        Invariants: {
            tiers: {
                tier_id: string;
                held: number;
                active_offer_units: number;
                capacity: number;
            }[];
            oversell: number;
            /** @description seat rows inconsistent with their offer; 0 when healthy */
            seat_mismatch?: number;
            held_mismatch: number;
            double_redemption: number;
        };
        Checkout: {
            /** @constant */
            provider: "razorpay";
            key_id: string;
            provider_order_id: string;
            amount_paise: number;
            /** @constant */
            currency: "INR";
            /** Format: date-time */
            pay_deadline: string;
        };
        MockPayment: {
            order_id: string;
            /**
             * @default mock
             * @constant
             */
            provider: "mock";
            /** @enum {string} */
            result: "success" | "fail";
        };
        RazorpayPayment: {
            order_id: string;
            /** @constant */
            provider: "razorpay";
            razorpay_order_id: string;
            razorpay_payment_id: string;
            razorpay_signature: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
